name: Terraform AWS EKS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up AWS Credentials
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      # Terraform Init
      - name: Terraform Init
        run: terraform init -input=false -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="key=eks-cluster/terraform.tfstate" -backend-config="region=${{ secrets.AWS_REGION }}"

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
